name: aag
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.2.2=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=hd77b12b_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.24.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py312haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.13=h2bbff1b_2
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py312haa95532_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.3=h1d929f7_1
  - pywin32=305=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - setuptools=69.5.1=py312haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.3.3=py312h2bbff1b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - vc=14.2=h2eaa2aa_1
  - vs2015_runtime=14.29.30133=h43f2093_3
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cramjam==2.8.3
      - cycler==0.12.1
      - fastparquet==2024.5.0
      - fonttools==4.52.4
      - fsspec==2024.5.0
      - idna==3.7
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pandas==2.2.2
      - pgeocode==0.5.0
      - pillow==10.3.0
      - pyarrow==16.1.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - threadpoolctl==3.5.0
      - tzdata==2024.1
      - urllib3==2.2.1